### ISSUE TITLE
Traffic count not displaying in Firefox

### ISSUE THREAD

**Issue by maya** [codeforamerica/city-analytics-dashboard#15]
![screen shot 2014-06-11 at 10 49 05 am](https://cloud.githubusercontent.com/assets/5249443/3248663/e82720e0-f190-11e3-8781-0790911539c7.png)

**Comment by milafrerichs** [comment]
fixed in https://github.com/codeforamerica/city-analytics-dashboard/commit/622fe572c56bc155e04cb1e9b93db97e79fd726d
