### ISSUE TITLE
Overlapping text

### ISSUE THREAD

**Issue by jmadans** [codeforamerica/city-analytics-dashboard#31]
on the live search and active page columns. 
![screen shot 2015-02-08 at 3 15 44 pm](https://cloud.githubusercontent.com/assets/1261618/6099127/807b8598-afa5-11e4-99e0-3d67f630722c.png)

**Comment by phae** [comment]
It's because of request animation frame that @slightlyoff added.

**Comment by jmadans** [comment]
@slightlyoff god bless you!
