### ISSUE TITLE
Incorrect date parameters requested

### ISSUE THREAD

**Issue by migurski** [codeforamerica/city-analytics-dashboard#39]
I’m seeing requests like this:

    method=GET path="/historic?ids=ga:1935932&dimensions=ga%3AnthMinute&metrics=ga%3Asessions&start-date=2015-03-1&end-date=2015-03-02&max-results=1000"

Note the date `2015-03-1`, which triggers this error:

     "Invalid value '2015-03-1'. Values must match the following regular expression: '[0-9]{4}-[0-9]{2}-[0-9]{2}|today|yesterday|[0-9]+(daysAgo)'"

**Comment by phae** [comment]
Oh. Huh. Should be a simple fix - it's just a missing 0 for single digit
dates. My bad.
